data:  
  - 
    name: "multi_vqa"
    type: huggingface
    path: "TIGER-Lab/Mantis-Instruct"
    format: chat
    split: train
    revision: script
    max_image_size: 728
  # - 
  #   name: "star"
  #   type: huggingface
  #   path: "TIGER-Lab/Mantis-Instruct"
  #   format: chat
  #   split: train
  #   revision: script
  # - 
  #   name: "visual_story_telling"
  #   type: huggingface
  #   path: "TIGER-Lab/Mantis-Instruct"
  #   format: chat
  #   split: train
  #   max_num_images: 8
  #   revision: script
  # - 
  #   name: "contrastive_caption"
  #   type: huggingface
  #   path: "TIGER-Lab/Mantis-Instruct"
  #   format: chat
  #   split: train
  #   revision: script
  # - 
  #   name: "imagecode"
  #   type: huggingface
  #   path: "TIGER-Lab/Mantis-Instruct"
  #   format: chat
  #   split: train
  #   shuffle: true
  #   revision: script