data:
  - 
    name: "nlvr2"
    type: huggingface
    path: "TIGER-Lab/Mantis-Instruct"
    format: chat
    split: train
    shuffle: true
    offline_sha: 11293b396d9be943fd8e4795ca703a76a0c2a0cc3b8cef295a3b6bf4bb8ea344
  - 
    name: "dreamsim"
    type: huggingface
    path: "TIGER-Lab/Mantis-Instruct"
    format: chat
    split: train
    offline_sha: 11293b396d9be943fd8e4795ca703a76a0c2a0cc3b8cef295a3b6bf4bb8ea344
  - 
    name: "contrastive_caption"
    type: huggingface
    path: "TIGER-Lab/Mantis-Instruct"
    format: chat
    split: train
    offline_sha: 11293b396d9be943fd8e4795ca703a76a0c2a0cc3b8cef295a3b6bf4bb8ea344
  - 
    name: "birds-to-words"    
    type: huggingface
    path: "TIGER-Lab/Mantis-Instruct"
    format: chat
    split: train
    offline_sha: 11293b396d9be943fd8e4795ca703a76a0c2a0cc3b8cef295a3b6bf4bb8ea344
  - 
    name: "visual_story_telling"
    type: huggingface
    path: "TIGER-Lab/Mantis-Instruct"
    format: chat
    split: train
    max_num_images: 20
    offline_sha: 11293b396d9be943fd8e4795ca703a76a0c2a0cc3b8cef295a3b6bf4bb8ea344
  -
    name: "spot-the-diff"
    type: huggingface
    path: "TIGER-Lab/Mantis-Instruct"
    format: chat
    split: train
    offline_sha: 11293b396d9be943fd8e4795ca703a76a0c2a0cc3b8cef295a3b6bf4bb8ea344
  - 
    name: "lrv"
    type: huggingface
    path: "TIGER-Lab/Mantis-Instruct"
    format: chat
    split: train
    offline_sha: 11293b396d9be943fd8e4795ca703a76a0c2a0cc3b8cef295a3b6bf4bb8ea344
  - 
    name: "nextqa"
    type: huggingface
    path: "TIGER-Lab/Mantis-Instruct"
    format: chat
    split: train
  - 
    name: "star"
    type: huggingface
    path: "TIGER-Lab/Mantis-Instruct"
    format: chat
    split: train
    offline_sha: 11293b396d9be943fd8e4795ca703a76a0c2a0cc3b8cef295a3b6bf4bb8ea344
  - 
    name: "llava_665k_multi"
    type: huggingface
    path: "TIGER-Lab/Mantis-Instruct"
    format: chat
    split: train
    shuffle: true
    offline_sha: 11293b396d9be943fd8e4795ca703a76a0c2a0cc3b8cef295a3b6bf4bb8ea344
  - 
    name: "coinstruct"
    type: huggingface
    path: "TIGER-Lab/Mantis-Instruct"
    format: chat
    split: train
    max_size: 100000 # 150K original
    shuffle: true
    offline_sha: 11293b396d9be943fd8e4795ca703a76a0c2a0cc3b8cef295a3b6bf4bb8ea344
  - 
    name: "dvqa"
    type: huggingface
    path: "TIGER-Lab/Mantis-Instruct"
    format: chat
    split: train
    max_size: 30000 # 200k original
    shuffle: true
    offline_sha: 11293b396d9be943fd8e4795ca703a76a0c2a0cc3b8cef295a3b6bf4bb8ea344
  - 
    name: "chartqa"
    type: huggingface
    path: "TIGER-Lab/Mantis-Instruct"
    format: chat
    split: train
    shuffle: true
    offline_sha: 11293b396d9be943fd8e4795ca703a76a0c2a0cc3b8cef295a3b6bf4bb8ea344
  - 
    name: "docvqa"
    type: huggingface
    path: "TIGER-Lab/Mantis-Instruct"
    format: chat
    split: train
    shuffle: true
    offline_sha: 11293b396d9be943fd8e4795ca703a76a0c2a0cc3b8cef295a3b6bf4bb8ea344
  - 
    name: "multi_vqa"
    type: huggingface
    path: "TIGER-Lab/Mantis-Instruct"
    format: chat
    split: train
    shuffle: true
    offline_sha: 11293b396d9be943fd8e4795ca703a76a0c2a0cc3b8cef295a3b6bf4bb8ea344
  - 
    name: "iconqa"
    type: huggingface
    path: "TIGER-Lab/Mantis-Instruct"
    format: chat
    split: train
    shuffle: true
    offline_sha: 11293b396d9be943fd8e4795ca703a76a0c2a0cc3b8cef295a3b6bf4bb8ea344
  - 
    name: "imagecode"
    type: huggingface
    path: "TIGER-Lab/Mantis-Instruct"
    format: chat
    split: train
    shuffle: true
    offline_sha: 11293b396d9be943fd8e4795ca703a76a0c2a0cc3b8cef295a3b6bf4bb8ea344

