name: mantis
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - bzip2=1.0.8=h5eee18b_5
  - ca-certificates=2024.3.11=h06a4308_0
  - certifi=2024.2.2=py39h06a4308_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.4.127=0
  - cuda-runtime=12.1.0=0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=py39h06a4308_0
  - freetype=2.12.1=h4a9f257_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py39heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - idna=3.4=py39h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.3=py39h06a4308_0
  - jpeg=9e=h5eee18b_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.9.1.3=0
  - libcurand=10.3.5.147=0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.17=h5eee18b_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libnpp=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libwebp-base=1.3.2=h5eee18b_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_0
  - markupsafe=2.1.3=py39h5eee18b_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py39h5eee18b_1
  - mkl_fft=1.3.8=py39h5eee18b_0
  - mkl_random=1.2.4=py39hdb19cb5_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py39h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.1=py39h06a4308_0
  - numpy=1.26.4=py39h5f9d8c6_0
  - numpy-base=1.26.4=py39hb5e798b_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=3.0.13=h7f8727e_0
  - pillow=10.2.0=py39h5eee18b_0
  - pip=23.3.1=py39h06a4308_0
  - python=3.9.19=h955ad1f_0
  - pytorch=2.2.2=py3.9_cuda12.1_cudnn8.9.2_0
  - pytorch-cuda=12.1=ha16c6d3_5
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.1=py39h5eee18b_0
  - readline=8.2=h5eee18b_0
  - requests=2.31.0=py39h06a4308_1
  - setuptools=68.2.2=py39h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - sympy=1.12=py39h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.12=h1ccaba5_0
  - torchaudio=2.2.2=py39_cu121
  - torchtriton=2.2.0=py39
  - torchvision=0.17.2=py39_cu121
  - typing_extensions=4.9.0=py39h06a4308_1
  - urllib3=2.1.0=py39h06a4308_0
  - wheel=0.41.2=py39h06a4308_0
  - xz=5.4.6=h5eee18b_0
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - accelerate==0.29.2
      - aiofiles==23.2.1
      - aiohttp==3.9.4
      - aiosignal==1.3.1
      - altair==5.3.0
      - annotated-types==0.6.0
      - anyio==4.3.0
      - appdirs==1.4.4
      - async-timeout==4.0.3
      - attrs==23.2.0
      - bitsandbytes==0.43.1
      - braceexpand==0.1.7
      - chardet==5.2.0
      - click==8.1.7
      - cloudpickle==3.0.0
      - contourpy==1.2.1
      - cycler==0.12.1
      - dask==2024.4.1
      - datasets==2.18.0
      - deepspeed==0.14.0
      - dill==0.3.8
      - distro==1.9.0
      - docker-pycreds==0.4.0
      - easy-openai==0.0.1
      - einops==0.7.0
      - eval-type-backport==0.1.3
      - exceptiongroup==1.2.0
      - fastapi==0.110.1
      - ffmpy==0.3.2
      - fire==0.6.0
      - flash-attn==2.5.7
      - fonttools==4.51.0
      - frozenlist==1.4.1
      - fsspec==2024.2.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - gradio==4.26.0
      - gradio-client==0.15.1
      - h11==0.14.0
      - hjson==3.1.0
      - httpcore==1.0.5
      - httpx==0.27.0
      - huggingface-hub==0.22.2
      - importlib-metadata==7.1.0
      - importlib-resources==6.4.0
      - iniconfig==2.0.0
      - jsonschema==4.21.1
      - jsonschema-specifications==2023.12.1
      - kiwisolver==1.4.5
      - locket==1.0.0
      - markdown-it-py==3.0.0
      - matplotlib==3.8.4
      - mdurl==0.1.2
      - multidict==6.0.5
      - multiprocess==0.70.16
      - ninja==1.11.1.1
      - openai==1.17.0
      - opencv-python==4.9.0.80
      - orjson==3.10.0
      - packaging==24.0
      - pandas==2.2.2
      - partd==1.4.1
      - peft==0.10.0
      - pluggy==1.4.0
      - prettytable==3.10.0
      - protobuf==4.25.3
      - psutil==5.9.8
      - py-cpuinfo==9.0.0
      - pyarrow==15.0.2
      - pyarrow-hotfix==0.6
      - pydantic==2.7.0
      - pydantic-core==2.18.1
      - pydub==0.25.1
      - pygments==2.17.2
      - pynvml==11.5.0
      - pyparsing==3.1.2
      - pytest==8.1.1
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.9
      - pytz==2024.1
      - referencing==0.34.0
      - regex==2023.12.25
      - rich==13.7.1
      - rpds-py==0.18.0
      - ruff==0.3.7
      - safetensors==0.4.2
      - scipy==1.13.0
      - semantic-version==2.10.0
      - sentencepiece==0.2.0
      - sentry-sdk==1.45.0
      - setproctitle==1.3.3
      - shellingham==1.5.4
      - six==1.16.0
      - smmap==5.0.1
      - sniffio==1.3.1
      - spaces==0.26.0
      - starlette==0.37.2
      - termcolor==2.4.0
      - tiktoken==0.6.0
      - tokenizers==0.15.2
      - tomli==2.0.1
      - tomlkit==0.12.0
      - toolz==0.12.1
      - tqdm==4.66.2
      - transformers==4.39.3
      - transformers-stream-generator==0.0.5
      - typer==0.12.3
      - tzdata==2024.1
      - uvicorn==0.29.0
      - wandb==0.16.6
      - wcwidth==0.2.13
      - webdataset==0.2.86
      - websockets==11.0.3
      - xxhash==3.4.1
      - yarl==1.9.4
      - zipp==3.18.1
prefix: /home/dongfu/miniconda3/envs/mantis
